/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package revisi_mentalhealth_care;

import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class DiaryUser extends javax.swing.JFrame {
    public void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("No");
        model.addColumn("Date");
        model.addColumn("Title");
        model.addColumn("About");
                
        try{
            int no = 1;
            String sql = "SELECT date, title, diary FROM catatan";
            java.sql.Connection conn = (java.sql.Connection)koneksi_database.koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
                model.addRow(new Object[]{no++,rs.getString(1),rs.getString(2), rs.getString(3)});
                
                tabelDiary.setModel(model);
            }
        
        }catch(SQLException e){
            System.out.println("ERROR :" +e.getMessage());
        }
    }
    /**
     * Creates new form Catatan_Kecil
     */
    public DiaryUser() {
        initComponents();
        tampilkan_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDiary = new javax.swing.JTable();
        InputTitle = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        IsiDiary = new javax.swing.JTextArea();
        ButtonDone = new javax.swing.JButton();
        ButtonBack = new javax.swing.JButton();
        JudulDiary2 = new javax.swing.JLabel();
        JudulDiary1 = new javax.swing.JLabel();
        LabelDiaryContent = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(77, 150, 255));

        tabelDiary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Title", "Diary"
            }
        ));
        tabelDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDiaryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDiary);

        InputTitle.setText("Title");
        InputTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InputTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InputTitleMouseClicked(evt);
            }
        });
        InputTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTitleActionPerformed(evt);
            }
        });

        IsiDiary.setColumns(20);
        IsiDiary.setRows(5);
        IsiDiary.setText("Text");
        IsiDiary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IsiDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IsiDiaryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(IsiDiary);

        ButtonDone.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ButtonDone.setText("DONE");
        ButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDoneActionPerformed(evt);
            }
        });

        ButtonBack.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        ButtonBack.setText("Back To Main Menu");
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        JudulDiary2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        JudulDiary2.setForeground(new java.awt.Color(255, 255, 255));
        JudulDiary2.setText("A Sanctuary, vent to your heart's content.");

        JudulDiary1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        JudulDiary1.setText("My Personal Diary");

        LabelDiaryContent.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        LabelDiaryContent.setForeground(new java.awt.Color(255, 255, 255));
        LabelDiaryContent.setText("Diary Content");

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LabelDiaryContent))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, BackgroundLayout.createSequentialGroup()
                                        .addComponent(InputTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ButtonDone, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(ButtonBack))))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JudulDiary1)
                            .addComponent(JudulDiary2))))
                .addGap(42, 42, 42))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(JudulDiary1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(JudulDiary2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelDiaryContent, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonDone)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTitleActionPerformed

    private void ButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDoneActionPerformed
        String title = InputTitle.getText();
        String diary = IsiDiary.getText();
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String date = String.valueOf(fm.format(Date.getDate()));
        try{
                String sql = "insert into catatan VALUES ('" + date +"','"+ title +"','"+ diary +"')";
                java.sql.Connection conn = (java.sql.Connection)koneksi_database.koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null,"Data Tersimpan");
            }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
            }
        tampilkan_data();
    }//GEN-LAST:event_ButtonDoneActionPerformed

    private void tabelDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDiaryMouseClicked
        int baris = tabelDiary.rowAtPoint(evt.getPoint());
        
        String ttl = tabelDiary.getValueAt(baris, 2).toString();
        InputTitle.setText(ttl);
        InputTitle.setForeground(Color.black);
        
        String dry = tabelDiary.getValueAt(baris, 3).toString();
        IsiDiary.setText(dry);
        IsiDiary.setForeground(Color.black);
    }//GEN-LAST:event_tabelDiaryMouseClicked

    private void InputTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InputTitleMouseClicked
        InputTitle.setText("");
    }//GEN-LAST:event_InputTitleMouseClicked

    private void IsiDiaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IsiDiaryMouseClicked
        IsiDiary.setText("");
    }//GEN-LAST:event_IsiDiaryMouseClicked

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        new TampilanUser().show();
        this.dispose();
    }//GEN-LAST:event_ButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiaryUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiaryUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiaryUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiaryUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiaryUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton ButtonBack;
    private javax.swing.JButton ButtonDone;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JTextField InputTitle;
    private javax.swing.JTextArea IsiDiary;
    private javax.swing.JLabel JudulDiary1;
    private javax.swing.JLabel JudulDiary2;
    private javax.swing.JLabel LabelDiaryContent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelDiary;
    // End of variables declaration//GEN-END:variables
}
