/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package revisi_mentalhealth_care;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import revisi_mentalhealth_care.Login;
/**
 *
 * @author Aspire 5
 */
public class MenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public MenuUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        ButtonLogOut = new javax.swing.JButton();
        ButtonDiary = new javax.swing.JButton();
        Background2 = new javax.swing.JPanel();
        Background3 = new javax.swing.JPanel();
        ButtonAppointment = new javax.swing.JButton();
        ButtonRecords = new javax.swing.JButton();
        BackGround1 = new javax.swing.JPanel();
        LabelGreetingUser = new javax.swing.JLabel();
        LabelGreetingUser2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InnerPeace");
        setName("MenuUser"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(709, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo innepeace1.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 260, 440));

        ButtonLogOut.setBackground(java.awt.Color.pink);
        ButtonLogOut.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ButtonLogOut.setForeground(new java.awt.Color(0, 102, 153));
        ButtonLogOut.setText("Log Out");
        ButtonLogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonLogOut.setBorderPainted(false);
        ButtonLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonLogOutMouseExited(evt);
            }
        });
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 150, 40));

        ButtonDiary.setBackground(java.awt.Color.pink);
        ButtonDiary.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonDiary.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDiary.setText("My Personal Diary");
        ButtonDiary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonDiary.setBorderPainted(false);
        ButtonDiary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonDiary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonDiaryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonDiaryMouseExited(evt);
            }
        });
        ButtonDiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiaryActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 340, 60));

        Background2.setBackground(new java.awt.Color(255, 255, 255));

        Background3.setBackground(new java.awt.Color(150, 204, 255));

        ButtonAppointment.setBackground(java.awt.Color.pink);
        ButtonAppointment.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonAppointment.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAppointment.setText("Make an Appointment");
        ButtonAppointment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonAppointment.setBorderPainted(false);
        ButtonAppointment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAppointmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAppointmentMouseExited(evt);
            }
        });
        ButtonAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAppointmentActionPerformed(evt);
            }
        });

        ButtonRecords.setBackground(java.awt.Color.pink);
        ButtonRecords.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonRecords.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRecords.setText("My Records");
        ButtonRecords.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonRecords.setBorderPainted(false);
        ButtonRecords.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonRecordsMouseExited(evt);
            }
        });
        ButtonRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Background3Layout = new javax.swing.GroupLayout(Background3);
        Background3.setLayout(Background3Layout);
        Background3Layout.setHorizontalGroup(
            Background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(Background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(318, Short.MAX_VALUE))
        );
        Background3Layout.setVerticalGroup(
            Background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background3Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(ButtonAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Background2Layout = new javax.swing.GroupLayout(Background2);
        Background2.setLayout(Background2Layout);
        Background2Layout.setHorizontalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Background2Layout.setVerticalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 710, 360));

        BackGround1.setBackground(new java.awt.Color(77, 150, 255));
        BackGround1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelGreetingUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        LabelGreetingUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelGreetingUser.setText("Hello there :)");
        BackGround1.add(LabelGreetingUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 400, 70));

        LabelGreetingUser2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        LabelGreetingUser2.setForeground(new java.awt.Color(255, 255, 255));
        LabelGreetingUser2.setText("How can we help?");
        BackGround1.add(LabelGreetingUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 400, 70));

        getContentPane().add(BackGround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiaryActionPerformed
        new DiaryUser().show();
        this.dispose();
    }//GEN-LAST:event_ButtonDiaryActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Log Out?", "", JOptionPane.YES_NO_OPTION);
        if(response==JOptionPane.YES_OPTION) {
            new Login().show();
            this.dispose();
        }
    }//GEN-LAST:event_ButtonLogOutActionPerformed

    private void ButtonAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAppointmentActionPerformed
        new JanjiTemu_User().show();
        this.dispose();
    }//GEN-LAST:event_ButtonAppointmentActionPerformed

    private void ButtonDiaryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDiaryMouseEntered
        ButtonDiary.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonDiaryMouseEntered

    private void ButtonDiaryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonDiaryMouseExited
        ButtonDiary.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonDiaryMouseExited

    private void ButtonAppointmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAppointmentMouseEntered
        ButtonAppointment.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonAppointmentMouseEntered

    private void ButtonAppointmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAppointmentMouseExited
        ButtonAppointment.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonAppointmentMouseExited

    private void ButtonLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogOutMouseEntered
        ButtonLogOut.setBackground(Color.lightGray);
    }//GEN-LAST:event_ButtonLogOutMouseEntered

    private void ButtonLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLogOutMouseExited
        ButtonLogOut.setBackground(Color.pink);
    }//GEN-LAST:event_ButtonLogOutMouseExited

    private void ButtonRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRecordsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRecordsMouseEntered

    private void ButtonRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRecordsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRecordsMouseExited

    private void ButtonRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRecordsActionPerformed
        new RekamMedis_User().show();
        this.dispose();
    }//GEN-LAST:event_ButtonRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround1;
    private javax.swing.JPanel Background2;
    private javax.swing.JPanel Background3;
    private javax.swing.JButton ButtonAppointment;
    private javax.swing.JButton ButtonDiary;
    private javax.swing.JButton ButtonLogOut;
    private javax.swing.JButton ButtonRecords;
    private javax.swing.JLabel LabelGreetingUser;
    private javax.swing.JLabel LabelGreetingUser2;
    private javax.swing.JLabel Logo;
    // End of variables declaration//GEN-END:variables
    
}
