/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package revisi_mentalhealth_care;

/**
 *
 * @author HP
 */
public class TampilanUser extends javax.swing.JFrame {

    /**
     * Creates new form TampilanUser
     */
    public TampilanUser() {
        initComponents();
        LabelGreeting.setText("Hello, " + Login.username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background2 = new javax.swing.JPanel();
        Background1 = new javax.swing.JPanel();
        LabelGreeting = new javax.swing.JLabel();
        Background3 = new javax.swing.JPanel();
        ButtonDiary = new javax.swing.JButton();
        ButtonAppointment = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        ButtonRecords = new javax.swing.JButton();
        ButtonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background2.setBackground(new java.awt.Color(255, 255, 255));

        Background1.setBackground(new java.awt.Color(77, 150, 255));

        LabelGreeting.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        LabelGreeting.setForeground(new java.awt.Color(255, 255, 255));
        LabelGreeting.setText("Hello,");

        javax.swing.GroupLayout Background1Layout = new javax.swing.GroupLayout(Background1);
        Background1.setLayout(Background1Layout);
        Background1Layout.setHorizontalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LabelGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Background1Layout.setVerticalGroup(
            Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelGreeting, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Background3.setBackground(new java.awt.Color(150, 204, 255));
        Background3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonDiary.setBackground(java.awt.Color.pink);
        ButtonDiary.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        ButtonDiary.setForeground(new java.awt.Color(255, 255, 255));
        ButtonDiary.setText("My Personal Diary");
        ButtonDiary.setBorder(null);
        ButtonDiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDiaryActionPerformed(evt);
            }
        });
        Background3.add(ButtonDiary, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 290, 50));

        ButtonAppointment.setBackground(java.awt.Color.pink);
        ButtonAppointment.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        ButtonAppointment.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAppointment.setText("Make an Appointment");
        ButtonAppointment.setBorder(null);
        ButtonAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAppointmentActionPerformed(evt);
            }
        });
        Background3.add(ButtonAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 290, 50));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo innepeace1.png"))); // NOI18N
        Background3.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 220, -1));

        Label2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        Label2.setForeground(new java.awt.Color(255, 255, 255));
        Label2.setText("How can we help?");
        Background3.add(Label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 44));

        ButtonRecords.setBackground(java.awt.Color.pink);
        ButtonRecords.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonRecords.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRecords.setText("My Records");
        ButtonRecords.setBorder(null);
        ButtonRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRecordsActionPerformed(evt);
            }
        });
        Background3.add(ButtonRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 260, 290, 50));

        ButtonLogOut.setBackground(java.awt.Color.pink);
        ButtonLogOut.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLogOut.setText("Log Out");
        ButtonLogOut.setBorder(null);
        ButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogOutActionPerformed(evt);
            }
        });
        Background3.add(ButtonLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 140, 40));

        javax.swing.GroupLayout Background2Layout = new javax.swing.GroupLayout(Background2);
        Background2.setLayout(Background2Layout);
        Background2Layout.setHorizontalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Background2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background3, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                .addContainerGap())
        );
        Background2Layout.setVerticalGroup(
            Background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background2Layout.createSequentialGroup()
                .addComponent(Background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDiaryActionPerformed
        new DiaryUser().show();
        this.dispose();
    }//GEN-LAST:event_ButtonDiaryActionPerformed

    private void ButtonAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAppointmentActionPerformed
        new JanjiTemu_User().show();
        this.dispose();
    }//GEN-LAST:event_ButtonAppointmentActionPerformed

    private void ButtonRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRecordsActionPerformed
        new Record_User().show();
        this.dispose();
    }//GEN-LAST:event_ButtonRecordsActionPerformed

    private void ButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogOutActionPerformed
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_ButtonLogOutActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background1;
    private javax.swing.JPanel Background2;
    private javax.swing.JPanel Background3;
    private javax.swing.JButton ButtonAppointment;
    private javax.swing.JButton ButtonDiary;
    private javax.swing.JButton ButtonLogOut;
    private javax.swing.JButton ButtonRecords;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel LabelGreeting;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
